version: '3.8'

services:
  auth_service:
    build:
      context: ./auth_service
    ports:
      - "5000:5000"
    networks:
      - vcc_network

  client_service:
    build:
      context: ./client_service
    ports:
      - "5001:5000"
    networks:
      - vcc_network
    depends_on:
      - auth_service

networks:
  vcc_network:
    driver: bridge

