version: '3'
services:
  auth_service:
    build:
      context: ./auth_service
    ports:
      - "8080:8080"
  
  client_service:
    build:
      context: ./client_service
    ports:
      - "5000:5000"  # Expose port 5000 for client service
    depends_on:
      - auth_service
